CC=gcc-13
FC=gfortran
LDF90=gfortran
CFLAGS=-g -O2 -fPIC
CXX=mpic++
CXXFLAGS=-O3 -fPIC -Wall -pedantic -std=c++17 -fno-gnu-unique -fopenmp
CXXFLAGS_NOOPENMP=-O3 -fPIC -Wall -pedantic -std=c++17 -fno-gnu-unique
CPPFLAGS= -DPACKAGE_NAME=\"PLUMED\" -DPACKAGE_TARNAME=\"plumed\" -DPACKAGE_VERSION=\"2\" -DPACKAGE_STRING=\"PLUMED\ 2\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -D__PLUMED_WRAPPER_LIBCXX11=1 -D__PLUMED_CXX17_FILESYSTEM=1 -D__PLUMED_HAS_MOLFILE_PLUGINS=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__PLUMED_HAS_DLADDR=1 -D__PLUMED_HAS_MPI=1 -D__PLUMED_HAS_ASMJIT=1 -D__PLUMED_HAS_DLOPEN=1 -D__PLUMED_HAS_RTLD_DEFAULT=1 -D__PLUMED_HAS_SUBPROCESS=1 -D__PLUMED_HAS_EXECINFO=1 -D__PLUMED_HAS_ZLIB=1 -D__PLUMED_HAS_PYTHON=1 -DNDEBUG=1 -D_REENTRANT=1 -D__PLUMED_PROGRAM_NAME=\"plumed\" -D__PLUMED_SOEXT=\"so\"
LDFLAGS=
DYNAMIC_LIBS= -lstdc++ -lz -ldl   -rdynamic -Wl,-Bsymbolic -fopenmp
LIBS=-ldl 
SOEXT=so
# LD is used only to link the plumed executable, so should be equivalent to the C++ compiler
LD=mpic++ -O3 -fPIC -Wall -pedantic -std=c++17 -fno-gnu-unique
LDSHARED=mpic++ -shared
LD_MAIN_RUNPATH=
GCCDEP=mpic++
disable_dependency_tracking=no
prefix=/usr/local
# use this variable to double check that prefix is not changed after configure
# (new in v2.5)
prefix_double_check=/usr/local
program_name=plumed
program_transform_name=s,x,x,
program_can_run_mpi=yes
program_can_run=yes
make_pdfdoc=no
make_doc=no
PACKAGE_TARNAME=plumed
LD_RO=ld -r -o
AR_CR=ar cr
exec_prefix=${prefix}
bindir=${exec_prefix}/bin
libdir=${exec_prefix}/lib
includedir=${prefix}/include
datarootdir=${prefix}/share
datadir=${datarootdir}
docdir=${datarootdir}/doc/${PACKAGE_TARNAME}
htmldir=${docdir}
python_bin=python3
plumed_found_cython=yes
canPyCV=
pybind11_cflags=
python_cf_embedded=
python_ld_embedded=
mpiexec=
make_static_archive=yes
use_absolute_soname=no
use_loader_path=no
use_debug_glibcxx=no
BASH_COMPLETION_DIR=
